# Generated by Django 4.1 on 2022-09-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelog",
            name="hours",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
